### ISSUE TITLE
flatpak-builder error

### ISSUE THREAD

**Issue by HenriWahl** [bellegarde-c/com.github.fwbuilder#1]
Hi there,
cool attempt to make fwbuilder work. +1

Does flatpak-builder produce something working for you? My attempt of `flatpak-builder fp_build com.github.fwbuilder.json
` leads to a compile error. I just wonder if it should work at all or I am doing something wrong.

Thanks for an answer and best regards.

**Comment by bellegarde-c** [comment]
No, was not working and did not have time to make this working :-( But on my TODO list to remove this  /usr/local/bin/fwbuilder on my Fedora.

**Comment by HenriWahl** [comment]
OK. Same problem here - getting rid of /usr/bin/local/fwbuilder.

So if I know this is not working I might take it as a start. I found problems when compiling net-snmp stuff - which do not occur if plainly compiling in non-flatpak environment. I will try to get this fixed.

**Comment by HenriWahl** [comment]
Do you know what this SNMP stuff is good for? The fwbuilder build process does not find the SNMP library header files, so I will try without.

**Comment by HenriWahl** [comment]
Solved by https://github.com/bellegarde-c/com.github.fwbuilder/pull/2
